name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Publish Images and Deploy
    runs-on: ubuntu-latest

    env:
      DOCKER_COMMAND: docker
      DOCKER_USERNAME: ganhammar
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - uses: actions/checkout@v4
      - name: Sign in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Publish Images
        shell: bash
        run: scripts/publish-images.sh
      - name: Deploy
        shell: bash
        run: scripts/main.sh
